apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscatalog.fullname" . }}
  labels:
    {{- include "vscatalog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vscatalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vscatalog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vscatalog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: RABBITMQ_USER
              value: {{ .Values.catalog.RabbitMQUser }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.catalog.RabbitMQPassword }}
            - name: RABBITMQ_IP
              value: {{ .Values.catalog.RabbitMQUrl }}
            - name: RABBITMQ_PORT
              value: {{ .Values.catalog.RabbitMQ_PORT }}
            - name: DB_CONNECTION_STRING
              value: {{ .Values.catalog.DatabaseConnectionString }}
            - name: RABBITMQ_QUEUE
              value: {{ .Values.catalog.RabbitMQqueue }}
            - name: ELASTICSEARCH_URL
              value: {{ .Values.catalog.elasticsearchUrl }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.catalog.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
