apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basketaria.fullname" . }}
  labels:
    {{- include "basketaria.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basketaria.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "basketaria.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "basketaria.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: RABBITMQ_USER
              value: {{ .Values.basket.RabbitMQUser }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.basket.RabbitMQPassword }}
            - name: RABBITMQ_IP
              value: {{ .Values.basket.RabbitMQUrl }}
            - name: BASE_KEY
              value: {{ .Values.basket.BaseKey }}
            - name: REDIS_IP
              value: {{ .Values.basket.RedisIP }}
            - name: REDIS_PORT
              value: {{ .Values.basket.RedisPort }}
            - name: RABBITMQ_PORT
              value: {{ .Values.basket.RabbitMQPort }}
            - name: RABBITMQ_QUEUE
              value: {{ .Values.basket.RabbitMQqueue }}
            - name: REDIS_PASSWORD
              value: {{ .Values.basket.RedisPWD }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
